// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestMuaHangTCTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver(@"C:\Users\Na\Desktop\TestShopQuanAo");
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    public void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void testMuaHangTC()
    {
        driver.Navigate().GoToUrl("http://localhost:27661/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".header__top__links:nth-child(1) > a")).Click();
        driver.FindElement(By.Name("username")).SendKeys("TK005");
        driver.FindElement(By.Name("pw")).SendKeys("123");
        driver.FindElement(By.Id("btnSignin")).Click();
        driver.FindElement(By.LinkText("Product")).Click();
        driver.FindElement(By.CssSelector("li:nth-child(4) > .list-group-item")).Click();


        WebDriverWait webDriverWait = new WebDriverWait(driver, new TimeSpan(10)); // đợi  element
        // Locating the Main Menu (Parent element)
        WebElement mainMenu = (WebElement)webDriverWait.Until(e => e.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .product__item__pic")));

        //Instantiating Actions class
        Actions actions = new Actions(driver);

        //Hovering on main menu
        actions.MoveToElement(mainMenu).Perform();

        Thread.Sleep(1000);

        // Locating the element from Sub Menu
        WebElement subMenu = (WebElement)driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) li:nth-child(2) img"));

        //To mouseover on sub menu
        actions.MoveToElement(subMenu);

        //build()- used to compile all the actions into a single step 
        actions.Click().Build().Perform();

        //driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) li:nth-child(2) img")).Click();
        driver.FindElement(By.CssSelector("label:nth-child(3)")).Click();
        driver.FindElement(By.CssSelector(".pro-qty")).Click();
        driver.FindElement(By.Name("txtsoluong")).SendKeys("-100"); // số lượng sản phẩm
        driver.FindElement(By.CssSelector(".primary-btn")).Click();
        driver.FindElement(By.CssSelector("label:nth-child(3)")).Click();
        driver.FindElement(By.CssSelector(".fa-angle-down")).Click();
        driver.FindElement(By.CssSelector(".primary-btn")).Click();
        Thread.Sleep(2000);
    }
    //public static void Hover(WebDriver driver, WebElement element)
    //{
    //    Actions builder = new Actions(driver);
    //    builder.MoveToElement(element).Perform();
    //}
    //public static void HoverAndClick(WebDriver driver, WebElement elementToHover, WebElement elementToClick)
    //{
    //    Actions builder = new Actions(driver);
    //    builder.MoveToElement(elementToHover).Click().Perform();
    //}
}
