// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class KhongNhapUsernameTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver(@"C:\Users\Na\Desktop\TestShopQuanAo");
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    public void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void khongNhapUsername()
    {
        driver.Navigate().GoToUrl("http://localhost:27661/TaiKhoan/DangKy");
        driver.Manage().Window.Size = new System.Drawing.Size(1040, 728);
        driver.FindElement(By.Name("UserName")).SendKeys(" ");
        driver.FindElement(By.Name("Pass")).SendKeys(" na123456");
        driver.FindElement(By.Name("RePass")).SendKeys(" na123456");
        driver.FindElement(By.Name("Ten")).SendKeys(" Lê Thùy Na");
        driver.FindElement(By.Name("NgaySinh")).SendKeys(" 17/05/2001");
        driver.FindElement(By.Name("Email")).SendKeys(" nalethuy@gmail.com");
        driver.FindElement(By.Name("SDT")).SendKeys(" 0362417182");
        driver.FindElement(By.Name("DiaChi")).SendKeys("TB");
        driver.FindElement(By.CssSelector(".btnSignUp")).Click();
        Assert.That(driver.FindElement(By.CssSelector(".form-floating:nth-child(2) > .field-validation-error")).Text, Is.EqualTo("Enter username"));
    }
}
