#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTAU")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANGLUONG(BANGLUONG instance);
    partial void UpdateBANGLUONG(BANGLUONG instance);
    partial void DeleteBANGLUONG(BANGLUONG instance);
    partial void InsertCTHAITRINH(CTHAITRINH instance);
    partial void UpdateCTHAITRINH(CTHAITRINH instance);
    partial void DeleteCTHAITRINH(CTHAITRINH instance);
    partial void InsertCTHOADON(CTHOADON instance);
    partial void UpdateCTHOADON(CTHOADON instance);
    partial void DeleteCTHOADON(CTHOADON instance);
    partial void Insertchitiettin(chitiettin instance);
    partial void Updatechitiettin(chitiettin instance);
    partial void Deletechitiettin(chitiettin instance);
    partial void InsertHAITRINH(HAITRINH instance);
    partial void UpdateHAITRINH(HAITRINH instance);
    partial void DeleteHAITRINH(HAITRINH instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void InsertLOAINV(LOAINV instance);
    partial void UpdateLOAINV(LOAINV instance);
    partial void DeleteLOAINV(LOAINV instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void Insertloaitin(loaitin instance);
    partial void Updateloaitin(loaitin instance);
    partial void Deleteloaitin(loaitin instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTAUTHUYEN(TAUTHUYEN instance);
    partial void UpdateTAUTHUYEN(TAUTHUYEN instance);
    partial void DeleteTAUTHUYEN(TAUTHUYEN instance);
    partial void InsertTOADOTAU(TOADOTAU instance);
    partial void UpdateTOADOTAU(TOADOTAU instance);
    partial void DeleteTOADOTAU(TOADOTAU instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLTAUConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BANGLUONG> BANGLUONGs
		{
			get
			{
				return this.GetTable<BANGLUONG>();
			}
		}
		
		public System.Data.Linq.Table<CTHAITRINH> CTHAITRINHs
		{
			get
			{
				return this.GetTable<CTHAITRINH>();
			}
		}
		
		public System.Data.Linq.Table<CTHOADON> CTHOADONs
		{
			get
			{
				return this.GetTable<CTHOADON>();
			}
		}
		
		public System.Data.Linq.Table<chitiettin> chitiettins
		{
			get
			{
				return this.GetTable<chitiettin>();
			}
		}
		
		public System.Data.Linq.Table<HAITRINH> HAITRINHs
		{
			get
			{
				return this.GetTable<HAITRINH>();
			}
		}
		
		public System.Data.Linq.Table<gia> gias
		{
			get
			{
				return this.GetTable<gia>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<LOAINV> LOAINVs
		{
			get
			{
				return this.GetTable<LOAINV>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<loaitin> loaitins
		{
			get
			{
				return this.GetTable<loaitin>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<TAUTHUYEN> TAUTHUYENs
		{
			get
			{
				return this.GetTable<TAUTHUYEN>();
			}
		}
		
		public System.Data.Linq.Table<TOADOTAU> TOADOTAUs
		{
			get
			{
				return this.GetTable<TOADOTAU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGLUONG")]
	public partial class BANGLUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _manv;
		
		private System.DateTime _ngaynhan;
		
		private System.Nullable<int> _songaylam;
		
		private System.Nullable<double> _thuong;
		
		private System.Nullable<double> _tongluong;
		
		private string _tinhtrang;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(int value);
    partial void OnmanvChanged();
    partial void OnngaynhanChanging(System.DateTime value);
    partial void OnngaynhanChanged();
    partial void OnsongaylamChanging(System.Nullable<int> value);
    partial void OnsongaylamChanged();
    partial void OnthuongChanging(System.Nullable<double> value);
    partial void OnthuongChanged();
    partial void OntongluongChanging(System.Nullable<double> value);
    partial void OntongluongChanged();
    partial void OntinhtrangChanging(string value);
    partial void OntinhtrangChanged();
    #endregion
		
		public BANGLUONG()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaynhan", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngaynhan
		{
			get
			{
				return this._ngaynhan;
			}
			set
			{
				if ((this._ngaynhan != value))
				{
					this.OnngaynhanChanging(value);
					this.SendPropertyChanging();
					this._ngaynhan = value;
					this.SendPropertyChanged("ngaynhan");
					this.OnngaynhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songaylam", DbType="Int")]
		public System.Nullable<int> songaylam
		{
			get
			{
				return this._songaylam;
			}
			set
			{
				if ((this._songaylam != value))
				{
					this.OnsongaylamChanging(value);
					this.SendPropertyChanging();
					this._songaylam = value;
					this.SendPropertyChanged("songaylam");
					this.OnsongaylamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuong", DbType="Float")]
		public System.Nullable<double> thuong
		{
			get
			{
				return this._thuong;
			}
			set
			{
				if ((this._thuong != value))
				{
					this.OnthuongChanging(value);
					this.SendPropertyChanging();
					this._thuong = value;
					this.SendPropertyChanged("thuong");
					this.OnthuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongluong", DbType="Float")]
		public System.Nullable<double> tongluong
		{
			get
			{
				return this._tongluong;
			}
			set
			{
				if ((this._tongluong != value))
				{
					this.OntongluongChanging(value);
					this.SendPropertyChanging();
					this._tongluong = value;
					this.SendPropertyChanged("tongluong");
					this.OntongluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="NVarChar(20)")]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_BANGLUONG", Storage="_NHANVIEN", ThisKey="manv", OtherKey="id", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.BANGLUONGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.BANGLUONGs.Add(this);
						this._manv = value.id;
					}
					else
					{
						this._manv = default(int);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHAITRINH")]
	public partial class CTHAITRINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mahaitrinh;
		
		private int _masp;
		
		private System.Nullable<double> _soluong;
		
		private System.Nullable<double> _thanhtien;
		
		private EntityRef<HAITRINH> _HAITRINH;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahaitrinhChanging(int value);
    partial void OnmahaitrinhChanged();
    partial void OnmaspChanging(int value);
    partial void OnmaspChanged();
    partial void OnsoluongChanging(System.Nullable<double> value);
    partial void OnsoluongChanged();
    partial void OnthanhtienChanging(System.Nullable<double> value);
    partial void OnthanhtienChanged();
    #endregion
		
		public CTHAITRINH()
		{
			this._HAITRINH = default(EntityRef<HAITRINH>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahaitrinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mahaitrinh
		{
			get
			{
				return this._mahaitrinh;
			}
			set
			{
				if ((this._mahaitrinh != value))
				{
					if (this._HAITRINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahaitrinhChanging(value);
					this.SendPropertyChanging();
					this._mahaitrinh = value;
					this.SendPropertyChanged("mahaitrinh");
					this.OnmahaitrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Float")]
		public System.Nullable<double> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Float")]
		public System.Nullable<double> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HAITRINH_CTHAITRINH", Storage="_HAITRINH", ThisKey="mahaitrinh", OtherKey="mahaitrinh", IsForeignKey=true)]
		public HAITRINH HAITRINH
		{
			get
			{
				return this._HAITRINH.Entity;
			}
			set
			{
				HAITRINH previousValue = this._HAITRINH.Entity;
				if (((previousValue != value) 
							|| (this._HAITRINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HAITRINH.Entity = null;
						previousValue.CTHAITRINHs.Remove(this);
					}
					this._HAITRINH.Entity = value;
					if ((value != null))
					{
						value.CTHAITRINHs.Add(this);
						this._mahaitrinh = value.mahaitrinh;
					}
					else
					{
						this._mahaitrinh = default(int);
					}
					this.SendPropertyChanged("HAITRINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_CTHAITRINH", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.CTHAITRINHs.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.CTHAITRINHs.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(int);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHOADON")]
	public partial class CTHOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mahd;
		
		private int _masp;
		
		private System.Nullable<double> _soluong;
		
		private System.Nullable<double> _gia;
		
		private System.Nullable<double> _thanhtien;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<sanpham> _sanpham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(int value);
    partial void OnmahdChanged();
    partial void OnmaspChanging(int value);
    partial void OnmaspChanged();
    partial void OnsoluongChanging(System.Nullable<double> value);
    partial void OnsoluongChanged();
    partial void OngiaChanging(System.Nullable<double> value);
    partial void OngiaChanged();
    partial void OnthanhtienChanging(System.Nullable<double> value);
    partial void OnthanhtienChanged();
    #endregion
		
		public CTHOADON()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._sanpham = default(EntityRef<sanpham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					if (this._sanpham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Float")]
		public System.Nullable<double> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Float")]
		public System.Nullable<double> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Float")]
		public System.Nullable<double> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHOADON", Storage="_HOADON", ThisKey="mahd", OtherKey="mahd", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CTHOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CTHOADONs.Add(this);
						this._mahd = value.mahd;
					}
					else
					{
						this._mahd = default(int);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_CTHOADON", Storage="_sanpham", ThisKey="masp", OtherKey="masp", IsForeignKey=true)]
		public sanpham sanpham
		{
			get
			{
				return this._sanpham.Entity;
			}
			set
			{
				sanpham previousValue = this._sanpham.Entity;
				if (((previousValue != value) 
							|| (this._sanpham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sanpham.Entity = null;
						previousValue.CTHOADONs.Remove(this);
					}
					this._sanpham.Entity = value;
					if ((value != null))
					{
						value.CTHOADONs.Add(this);
						this._masp = value.masp;
					}
					else
					{
						this._masp = default(int);
					}
					this.SendPropertyChanged("sanpham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitiettin")]
	public partial class chitiettin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matin;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _maloai;
		
		private string _anh;
		
		private string _link;
		
		private EntityRef<loaitin> _loaitin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatinChanging(int value);
    partial void OnmatinChanged();
    partial void OntieudeChanging(string value);
    partial void OntieudeChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydangChanged();
    partial void OnmaloaiChanging(System.Nullable<int> value);
    partial void OnmaloaiChanged();
    partial void OnanhChanging(string value);
    partial void OnanhChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public chitiettin()
		{
			this._loaitin = default(EntityRef<loaitin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int matin
		{
			get
			{
				return this._matin;
			}
			set
			{
				if ((this._matin != value))
				{
					this.OnmatinChanging(value);
					this.SendPropertyChanging();
					this._matin = value;
					this.SendPropertyChanged("matin");
					this.OnmatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(MAX)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this.OntieudeChanging(value);
					this.SendPropertyChanging();
					this._tieude = value;
					this.SendPropertyChanged("tieude");
					this.OntieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="Int")]
		public System.Nullable<int> maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._loaitin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anh", DbType="NVarChar(50)")]
		public string anh
		{
			get
			{
				return this._anh;
			}
			set
			{
				if ((this._anh != value))
				{
					this.OnanhChanging(value);
					this.SendPropertyChanging();
					this._anh = value;
					this.SendPropertyChanged("anh");
					this.OnanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(MAX)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaitin_chitiettin", Storage="_loaitin", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true)]
		public loaitin loaitin
		{
			get
			{
				return this._loaitin.Entity;
			}
			set
			{
				loaitin previousValue = this._loaitin.Entity;
				if (((previousValue != value) 
							|| (this._loaitin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaitin.Entity = null;
						previousValue.chitiettins.Remove(this);
					}
					this._loaitin.Entity = value;
					if ((value != null))
					{
						value.chitiettins.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(Nullable<int>);
					}
					this.SendPropertyChanged("loaitin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HAITRINH")]
	public partial class HAITRINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mahaitrinh;
		
		private string _matau;
		
		private System.Nullable<System.DateTime> _ngaydi;
		
		private System.Nullable<System.DateTime> _ngayve;
		
		private System.Nullable<double> _tongsanluong;
		
		private System.Nullable<double> _doanhthu;
		
		private System.Nullable<double> _dautieuthu;
		
		private System.Nullable<double> _giadau;
		
		private EntitySet<CTHAITRINH> _CTHAITRINHs;
		
		private EntityRef<TAUTHUYEN> _TAUTHUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahaitrinhChanging(int value);
    partial void OnmahaitrinhChanged();
    partial void OnmatauChanging(string value);
    partial void OnmatauChanged();
    partial void OnngaydiChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydiChanged();
    partial void OnngayveChanging(System.Nullable<System.DateTime> value);
    partial void OnngayveChanged();
    partial void OntongsanluongChanging(System.Nullable<double> value);
    partial void OntongsanluongChanged();
    partial void OndoanhthuChanging(System.Nullable<double> value);
    partial void OndoanhthuChanged();
    partial void OndautieuthuChanging(System.Nullable<double> value);
    partial void OndautieuthuChanged();
    partial void OngiadauChanging(System.Nullable<double> value);
    partial void OngiadauChanged();
    #endregion
		
		public HAITRINH()
		{
			this._CTHAITRINHs = new EntitySet<CTHAITRINH>(new Action<CTHAITRINH>(this.attach_CTHAITRINHs), new Action<CTHAITRINH>(this.detach_CTHAITRINHs));
			this._TAUTHUYEN = default(EntityRef<TAUTHUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahaitrinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mahaitrinh
		{
			get
			{
				return this._mahaitrinh;
			}
			set
			{
				if ((this._mahaitrinh != value))
				{
					this.OnmahaitrinhChanging(value);
					this.SendPropertyChanging();
					this._mahaitrinh = value;
					this.SendPropertyChanged("mahaitrinh");
					this.OnmahaitrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matau", DbType="Char(10)")]
		public string matau
		{
			get
			{
				return this._matau;
			}
			set
			{
				if ((this._matau != value))
				{
					if (this._TAUTHUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatauChanging(value);
					this.SendPropertyChanging();
					this._matau = value;
					this.SendPropertyChanged("matau");
					this.OnmatauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this.OnngaydiChanging(value);
					this.SendPropertyChanging();
					this._ngaydi = value;
					this.SendPropertyChanged("ngaydi");
					this.OnngaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayve", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayve
		{
			get
			{
				return this._ngayve;
			}
			set
			{
				if ((this._ngayve != value))
				{
					this.OnngayveChanging(value);
					this.SendPropertyChanging();
					this._ngayve = value;
					this.SendPropertyChanged("ngayve");
					this.OnngayveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongsanluong", DbType="Float")]
		public System.Nullable<double> tongsanluong
		{
			get
			{
				return this._tongsanluong;
			}
			set
			{
				if ((this._tongsanluong != value))
				{
					this.OntongsanluongChanging(value);
					this.SendPropertyChanging();
					this._tongsanluong = value;
					this.SendPropertyChanged("tongsanluong");
					this.OntongsanluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doanhthu", DbType="Float")]
		public System.Nullable<double> doanhthu
		{
			get
			{
				return this._doanhthu;
			}
			set
			{
				if ((this._doanhthu != value))
				{
					this.OndoanhthuChanging(value);
					this.SendPropertyChanging();
					this._doanhthu = value;
					this.SendPropertyChanged("doanhthu");
					this.OndoanhthuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dautieuthu", DbType="Float")]
		public System.Nullable<double> dautieuthu
		{
			get
			{
				return this._dautieuthu;
			}
			set
			{
				if ((this._dautieuthu != value))
				{
					this.OndautieuthuChanging(value);
					this.SendPropertyChanging();
					this._dautieuthu = value;
					this.SendPropertyChanged("dautieuthu");
					this.OndautieuthuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giadau", DbType="Float")]
		public System.Nullable<double> giadau
		{
			get
			{
				return this._giadau;
			}
			set
			{
				if ((this._giadau != value))
				{
					this.OngiadauChanging(value);
					this.SendPropertyChanging();
					this._giadau = value;
					this.SendPropertyChanged("giadau");
					this.OngiadauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HAITRINH_CTHAITRINH", Storage="_CTHAITRINHs", ThisKey="mahaitrinh", OtherKey="mahaitrinh")]
		public EntitySet<CTHAITRINH> CTHAITRINHs
		{
			get
			{
				return this._CTHAITRINHs;
			}
			set
			{
				this._CTHAITRINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAUTHUYEN_HAITRINH", Storage="_TAUTHUYEN", ThisKey="matau", OtherKey="matau", IsForeignKey=true)]
		public TAUTHUYEN TAUTHUYEN
		{
			get
			{
				return this._TAUTHUYEN.Entity;
			}
			set
			{
				TAUTHUYEN previousValue = this._TAUTHUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TAUTHUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAUTHUYEN.Entity = null;
						previousValue.HAITRINHs.Remove(this);
					}
					this._TAUTHUYEN.Entity = value;
					if ((value != null))
					{
						value.HAITRINHs.Add(this);
						this._matau = value.matau;
					}
					else
					{
						this._matau = default(string);
					}
					this.SendPropertyChanged("TAUTHUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHAITRINHs(CTHAITRINH entity)
		{
			this.SendPropertyChanging();
			entity.HAITRINH = this;
		}
		
		private void detach_CTHAITRINHs(CTHAITRINH entity)
		{
			this.SendPropertyChanging();
			entity.HAITRINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gia")]
	public partial class gia
	{
		
		private System.Nullable<System.DateTime> _ngaycapnhat;
		
		private System.Nullable<int> _masp;
		
		private System.Nullable<double> _gia1;
		
		public gia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaycapnhat", DbType="Date")]
		public System.Nullable<System.DateTime> ngaycapnhat
		{
			get
			{
				return this._ngaycapnhat;
			}
			set
			{
				if ((this._ngaycapnhat != value))
				{
					this._ngaycapnhat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Int")]
		public System.Nullable<int> masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					this._masp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="gia", Storage="_gia1", DbType="Float")]
		public System.Nullable<double> gia1
		{
			get
			{
				return this._gia1;
			}
			set
			{
				if ((this._gia1 != value))
				{
					this._gia1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mahd;
		
		private System.Nullable<int> _makh;
		
		private System.Nullable<double> _thanhtien;
		
		private System.Nullable<System.DateTime> _ngaylap;
		
		private string _tinhtrang;
		
		private EntitySet<CTHOADON> _CTHOADONs;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(int value);
    partial void OnmahdChanged();
    partial void OnmakhChanging(System.Nullable<int> value);
    partial void OnmakhChanged();
    partial void OnthanhtienChanging(System.Nullable<double> value);
    partial void OnthanhtienChanged();
    partial void OnngaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylapChanged();
    partial void OntinhtrangChanging(string value);
    partial void OntinhtrangChanged();
    #endregion
		
		public HOADON()
		{
			this._CTHOADONs = new EntitySet<CTHOADON>(new Action<CTHOADON>(this.attach_CTHOADONs), new Action<CTHOADON>(this.detach_CTHOADONs));
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="Int")]
		public System.Nullable<int> makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Float")]
		public System.Nullable<double> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this.OnthanhtienChanging(value);
					this.SendPropertyChanging();
					this._thanhtien = value;
					this.SendPropertyChanged("thanhtien");
					this.OnthanhtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="NVarChar(20)")]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CTHOADON", Storage="_CTHOADONs", ThisKey="mahd", OtherKey="mahd")]
		public EntitySet<CTHOADON> CTHOADONs
		{
			get
			{
				return this._CTHOADONs;
			}
			set
			{
				this._CTHOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_HOADON", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(Nullable<int>);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _makh;
		
		private string _tenkh;
		
		private string _sdt;
		
		private string _masothue;
		
		private string _diachi;
		
		private string _loaikh;
		
		private EntitySet<HOADON> _HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(int value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnmasothueChanging(string value);
    partial void OnmasothueChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnloaikhChanging(string value);
    partial void OnloaikhChanged();
    #endregion
		
		public khachhang()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="NVarChar(50)")]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Char(11)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masothue", DbType="Char(20)")]
		public string masothue
		{
			get
			{
				return this._masothue;
			}
			set
			{
				if ((this._masothue != value))
				{
					this.OnmasothueChanging(value);
					this.SendPropertyChanging();
					this._masothue = value;
					this.SendPropertyChanged("masothue");
					this.OnmasothueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaikh", DbType="Char(10)")]
		public string loaikh
		{
			get
			{
				return this._loaikh;
			}
			set
			{
				if ((this._loaikh != value))
				{
					this.OnloaikhChanging(value);
					this.SendPropertyChanging();
					this._loaikh = value;
					this.SendPropertyChanged("loaikh");
					this.OnloaikhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_HOADON", Storage="_HOADONs", ThisKey="makh", OtherKey="makh")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAINV")]
	public partial class LOAINV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloai;
		
		private string _tenloai;
		
		private System.Nullable<double> _luongcoban;
		
		private System.Nullable<double> _luongngay;
		
		private System.Nullable<double> _phucap;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OntenloaiChanging(string value);
    partial void OntenloaiChanged();
    partial void OnluongcobanChanging(System.Nullable<double> value);
    partial void OnluongcobanChanged();
    partial void OnluongngayChanging(System.Nullable<double> value);
    partial void OnluongngayChanged();
    partial void OnphucapChanging(System.Nullable<double> value);
    partial void OnphucapChanged();
    #endregion
		
		public LOAINV()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloai", DbType="NVarChar(20)")]
		public string tenloai
		{
			get
			{
				return this._tenloai;
			}
			set
			{
				if ((this._tenloai != value))
				{
					this.OntenloaiChanging(value);
					this.SendPropertyChanging();
					this._tenloai = value;
					this.SendPropertyChanged("tenloai");
					this.OntenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongcoban", DbType="Float")]
		public System.Nullable<double> luongcoban
		{
			get
			{
				return this._luongcoban;
			}
			set
			{
				if ((this._luongcoban != value))
				{
					this.OnluongcobanChanging(value);
					this.SendPropertyChanging();
					this._luongcoban = value;
					this.SendPropertyChanged("luongcoban");
					this.OnluongcobanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongngay", DbType="Float")]
		public System.Nullable<double> luongngay
		{
			get
			{
				return this._luongngay;
			}
			set
			{
				if ((this._luongngay != value))
				{
					this.OnluongngayChanging(value);
					this.SendPropertyChanging();
					this._luongngay = value;
					this.SendPropertyChanged("luongngay");
					this.OnluongngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phucap", DbType="Float")]
		public System.Nullable<double> phucap
		{
			get
			{
				return this._phucap;
			}
			set
			{
				if ((this._phucap != value))
				{
					this.OnphucapChanging(value);
					this.SendPropertyChanging();
					this._phucap = value;
					this.SendPropertyChanged("phucap");
					this.OnphucapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAINV_NHANVIEN", Storage="_NHANVIENs", ThisKey="maloai", OtherKey="maloai")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOAINV = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOAINV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _diachi;
		
		private string _mabhxh;
		
		private string _maloai;
		
		private string _matau;
		
		private string _cccd;
		
		private EntitySet<BANGLUONG> _BANGLUONGs;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
		private EntitySet<TAUTHUYEN> _TAUTHUYENs;
		
		private EntityRef<LOAINV> _LOAINV;
		
		private EntityRef<TAUTHUYEN> _TAUTHUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnmabhxhChanging(string value);
    partial void OnmabhxhChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OnmatauChanging(string value);
    partial void OnmatauChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._BANGLUONGs = new EntitySet<BANGLUONG>(new Action<BANGLUONG>(this.attach_BANGLUONGs), new Action<BANGLUONG>(this.detach_BANGLUONGs));
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			this._TAUTHUYENs = new EntitySet<TAUTHUYEN>(new Action<TAUTHUYEN>(this.attach_TAUTHUYENs), new Action<TAUTHUYEN>(this.detach_TAUTHUYENs));
			this._LOAINV = default(EntityRef<LOAINV>);
			this._TAUTHUYEN = default(EntityRef<TAUTHUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(30)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mabhxh", DbType="Char(12)")]
		public string mabhxh
		{
			get
			{
				return this._mabhxh;
			}
			set
			{
				if ((this._mabhxh != value))
				{
					this.OnmabhxhChanging(value);
					this.SendPropertyChanging();
					this._mabhxh = value;
					this.SendPropertyChanged("mabhxh");
					this.OnmabhxhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="Char(10)")]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._LOAINV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matau", DbType="Char(10)")]
		public string matau
		{
			get
			{
				return this._matau;
			}
			set
			{
				if ((this._matau != value))
				{
					if (this._TAUTHUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatauChanging(value);
					this.SendPropertyChanging();
					this._matau = value;
					this.SendPropertyChanged("matau");
					this.OnmatauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="Char(12)")]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_BANGLUONG", Storage="_BANGLUONGs", ThisKey="id", OtherKey="manv")]
		public EntitySet<BANGLUONG> BANGLUONGs
		{
			get
			{
				return this._BANGLUONGs;
			}
			set
			{
				this._BANGLUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="id", OtherKey="id")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAUTHUYEN", Storage="_TAUTHUYENs", ThisKey="id", OtherKey="thuyentruong")]
		public EntitySet<TAUTHUYEN> TAUTHUYENs
		{
			get
			{
				return this._TAUTHUYENs;
			}
			set
			{
				this._TAUTHUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAINV_NHANVIEN", Storage="_LOAINV", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true)]
		public LOAINV LOAINV
		{
			get
			{
				return this._LOAINV.Entity;
			}
			set
			{
				LOAINV previousValue = this._LOAINV.Entity;
				if (((previousValue != value) 
							|| (this._LOAINV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAINV.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._LOAINV.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(string);
					}
					this.SendPropertyChanged("LOAINV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAUTHUYEN_NHANVIEN", Storage="_TAUTHUYEN", ThisKey="matau", OtherKey="matau", IsForeignKey=true)]
		public TAUTHUYEN TAUTHUYEN
		{
			get
			{
				return this._TAUTHUYEN.Entity;
			}
			set
			{
				TAUTHUYEN previousValue = this._TAUTHUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TAUTHUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAUTHUYEN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._TAUTHUYEN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._matau = value.matau;
					}
					else
					{
						this._matau = default(string);
					}
					this.SendPropertyChanged("TAUTHUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGLUONGs(BANGLUONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_BANGLUONGs(BANGLUONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_TAUTHUYENs(TAUTHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TAUTHUYENs(TAUTHUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaitin")]
	public partial class loaitin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maloai;
		
		private string _tenloai;
		
		private EntitySet<chitiettin> _chitiettins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(int value);
    partial void OnmaloaiChanged();
    partial void OntenloaiChanging(string value);
    partial void OntenloaiChanged();
    #endregion
		
		public loaitin()
		{
			this._chitiettins = new EntitySet<chitiettin>(new Action<chitiettin>(this.attach_chitiettins), new Action<chitiettin>(this.detach_chitiettins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenloai", DbType="NVarChar(50)")]
		public string tenloai
		{
			get
			{
				return this._tenloai;
			}
			set
			{
				if ((this._tenloai != value))
				{
					this.OntenloaiChanging(value);
					this.SendPropertyChanging();
					this._tenloai = value;
					this.SendPropertyChanged("tenloai");
					this.OntenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaitin_chitiettin", Storage="_chitiettins", ThisKey="maloai", OtherKey="maloai")]
		public EntitySet<chitiettin> chitiettins
		{
			get
			{
				return this._chitiettins;
			}
			set
			{
				this._chitiettins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiettins(chitiettin entity)
		{
			this.SendPropertyChanging();
			entity.loaitin = this;
		}
		
		private void detach_chitiettins(chitiettin entity)
		{
			this.SendPropertyChanging();
			entity.loaitin = null;
		}

        internal bool Contains(string search)
        {
            throw new NotImplementedException();
        }
    }
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _masp;
		
		private string _tensp;
		
		private string _dvt;
		
		private System.Nullable<double> _sltong;
		
		private EntitySet<CTHAITRINH> _CTHAITRINHs;
		
		private EntitySet<CTHOADON> _CTHOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaspChanging(int value);
    partial void OnmaspChanged();
    partial void OntenspChanging(string value);
    partial void OntenspChanged();
    partial void OndvtChanging(string value);
    partial void OndvtChanged();
    partial void OnsltongChanging(System.Nullable<double> value);
    partial void OnsltongChanged();
    #endregion
		
		public sanpham()
		{
			this._CTHAITRINHs = new EntitySet<CTHAITRINH>(new Action<CTHAITRINH>(this.attach_CTHAITRINHs), new Action<CTHAITRINH>(this.detach_CTHAITRINHs));
			this._CTHOADONs = new EntitySet<CTHOADON>(new Action<CTHOADON>(this.attach_CTHOADONs), new Action<CTHOADON>(this.detach_CTHOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masp", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int masp
		{
			get
			{
				return this._masp;
			}
			set
			{
				if ((this._masp != value))
				{
					this.OnmaspChanging(value);
					this.SendPropertyChanging();
					this._masp = value;
					this.SendPropertyChanged("masp");
					this.OnmaspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensp", DbType="NVarChar(20)")]
		public string tensp
		{
			get
			{
				return this._tensp;
			}
			set
			{
				if ((this._tensp != value))
				{
					this.OntenspChanging(value);
					this.SendPropertyChanging();
					this._tensp = value;
					this.SendPropertyChanged("tensp");
					this.OntenspChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dvt", DbType="Char(10)")]
		public string dvt
		{
			get
			{
				return this._dvt;
			}
			set
			{
				if ((this._dvt != value))
				{
					this.OndvtChanging(value);
					this.SendPropertyChanging();
					this._dvt = value;
					this.SendPropertyChanged("dvt");
					this.OndvtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sltong", DbType="Float")]
		public System.Nullable<double> sltong
		{
			get
			{
				return this._sltong;
			}
			set
			{
				if ((this._sltong != value))
				{
					this.OnsltongChanging(value);
					this.SendPropertyChanging();
					this._sltong = value;
					this.SendPropertyChanged("sltong");
					this.OnsltongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_CTHAITRINH", Storage="_CTHAITRINHs", ThisKey="masp", OtherKey="masp")]
		public EntitySet<CTHAITRINH> CTHAITRINHs
		{
			get
			{
				return this._CTHAITRINHs;
			}
			set
			{
				this._CTHAITRINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sanpham_CTHOADON", Storage="_CTHOADONs", ThisKey="masp", OtherKey="masp")]
		public EntitySet<CTHOADON> CTHOADONs
		{
			get
			{
				return this._CTHOADONs;
			}
			set
			{
				this._CTHOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHAITRINHs(CTHAITRINH entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_CTHAITRINHs(CTHAITRINH entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
		
		private void attach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = this;
		}
		
		private void detach_CTHOADONs(CTHOADON entity)
		{
			this.SendPropertyChanging();
			entity.sanpham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tendangnhap;
		
		private string _matkhau;
		
		private System.Nullable<int> _id;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntendangnhapChanging(string value);
    partial void OntendangnhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnidChanging(System.Nullable<int> value);
    partial void OnidChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendangnhap", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tendangnhap
		{
			get
			{
				return this._tendangnhap;
			}
			set
			{
				if ((this._tendangnhap != value))
				{
					this.OntendangnhapChanging(value);
					this.SendPropertyChanging();
					this._tendangnhap = value;
					this.SendPropertyChanged("tendangnhap");
					this.OntendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(20)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_NHANVIEN", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._id = value.id;
					}
					else
					{
						this._id = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAUTHUYEN")]
	public partial class TAUTHUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matau;
		
		private string _loaitau;
		
		private System.Nullable<int> _thuyentruong;
		
		private EntitySet<HAITRINH> _HAITRINHs;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
		private EntitySet<TOADOTAU> _TOADOTAUs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatauChanging(string value);
    partial void OnmatauChanged();
    partial void OnloaitauChanging(string value);
    partial void OnloaitauChanged();
    partial void OnthuyentruongChanging(System.Nullable<int> value);
    partial void OnthuyentruongChanged();
    #endregion
		
		public TAUTHUYEN()
		{
			this._HAITRINHs = new EntitySet<HAITRINH>(new Action<HAITRINH>(this.attach_HAITRINHs), new Action<HAITRINH>(this.detach_HAITRINHs));
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			this._TOADOTAUs = new EntitySet<TOADOTAU>(new Action<TOADOTAU>(this.attach_TOADOTAUs), new Action<TOADOTAU>(this.detach_TOADOTAUs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matau", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matau
		{
			get
			{
				return this._matau;
			}
			set
			{
				if ((this._matau != value))
				{
					this.OnmatauChanging(value);
					this.SendPropertyChanging();
					this._matau = value;
					this.SendPropertyChanged("matau");
					this.OnmatauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaitau", DbType="NVarChar(20)")]
		public string loaitau
		{
			get
			{
				return this._loaitau;
			}
			set
			{
				if ((this._loaitau != value))
				{
					this.OnloaitauChanging(value);
					this.SendPropertyChanging();
					this._loaitau = value;
					this.SendPropertyChanged("loaitau");
					this.OnloaitauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuyentruong", DbType="Int")]
		public System.Nullable<int> thuyentruong
		{
			get
			{
				return this._thuyentruong;
			}
			set
			{
				if ((this._thuyentruong != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnthuyentruongChanging(value);
					this.SendPropertyChanging();
					this._thuyentruong = value;
					this.SendPropertyChanged("thuyentruong");
					this.OnthuyentruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAUTHUYEN_HAITRINH", Storage="_HAITRINHs", ThisKey="matau", OtherKey="matau")]
		public EntitySet<HAITRINH> HAITRINHs
		{
			get
			{
				return this._HAITRINHs;
			}
			set
			{
				this._HAITRINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAUTHUYEN_NHANVIEN", Storage="_NHANVIENs", ThisKey="matau", OtherKey="matau")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAUTHUYEN_TOADOTAU", Storage="_TOADOTAUs", ThisKey="matau", OtherKey="matau")]
		public EntitySet<TOADOTAU> TOADOTAUs
		{
			get
			{
				return this._TOADOTAUs;
			}
			set
			{
				this._TOADOTAUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAUTHUYEN", Storage="_NHANVIEN", ThisKey="thuyentruong", OtherKey="id", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAUTHUYENs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAUTHUYENs.Add(this);
						this._thuyentruong = value.id;
					}
					else
					{
						this._thuyentruong = default(Nullable<int>);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HAITRINHs(HAITRINH entity)
		{
			this.SendPropertyChanging();
			entity.TAUTHUYEN = this;
		}
		
		private void detach_HAITRINHs(HAITRINH entity)
		{
			this.SendPropertyChanging();
			entity.TAUTHUYEN = null;
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAUTHUYEN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAUTHUYEN = null;
		}
		
		private void attach_TOADOTAUs(TOADOTAU entity)
		{
			this.SendPropertyChanging();
			entity.TAUTHUYEN = this;
		}
		
		private void detach_TOADOTAUs(TOADOTAU entity)
		{
			this.SendPropertyChanging();
			entity.TAUTHUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOADOTAU")]
	public partial class TOADOTAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matau;
		
		private System.DateTime _thoigian;
		
		private string _latutude;
		
		private string _longitude;
		
		private EntityRef<TAUTHUYEN> _TAUTHUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatauChanging(string value);
    partial void OnmatauChanged();
    partial void OnthoigianChanging(System.DateTime value);
    partial void OnthoigianChanged();
    partial void OnlatutudeChanging(string value);
    partial void OnlatutudeChanged();
    partial void OnlongitudeChanging(string value);
    partial void OnlongitudeChanged();
    #endregion
		
		public TOADOTAU()
		{
			this._TAUTHUYEN = default(EntityRef<TAUTHUYEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matau", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matau
		{
			get
			{
				return this._matau;
			}
			set
			{
				if ((this._matau != value))
				{
					if (this._TAUTHUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatauChanging(value);
					this.SendPropertyChanging();
					this._matau = value;
					this.SendPropertyChanged("matau");
					this.OnmatauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigian", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime thoigian
		{
			get
			{
				return this._thoigian;
			}
			set
			{
				if ((this._thoigian != value))
				{
					this.OnthoigianChanging(value);
					this.SendPropertyChanging();
					this._thoigian = value;
					this.SendPropertyChanged("thoigian");
					this.OnthoigianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latutude", DbType="Char(10)")]
		public string latutude
		{
			get
			{
				return this._latutude;
			}
			set
			{
				if ((this._latutude != value))
				{
					this.OnlatutudeChanging(value);
					this.SendPropertyChanging();
					this._latutude = value;
					this.SendPropertyChanged("latutude");
					this.OnlatutudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Char(10)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAUTHUYEN_TOADOTAU", Storage="_TAUTHUYEN", ThisKey="matau", OtherKey="matau", IsForeignKey=true)]
		public TAUTHUYEN TAUTHUYEN
		{
			get
			{
				return this._TAUTHUYEN.Entity;
			}
			set
			{
				TAUTHUYEN previousValue = this._TAUTHUYEN.Entity;
				if (((previousValue != value) 
							|| (this._TAUTHUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAUTHUYEN.Entity = null;
						previousValue.TOADOTAUs.Remove(this);
					}
					this._TAUTHUYEN.Entity = value;
					if ((value != null))
					{
						value.TOADOTAUs.Add(this);
						this._matau = value.matau;
					}
					else
					{
						this._matau = default(string);
					}
					this.SendPropertyChanged("TAUTHUYEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
